spring:
  application:
    name: despesas
  #Mysql Local
  datasource:
    username: ${DB_USUARIO}
    password: ${DB_SENHA}
    url: jdbc:mysql://${DB_HOST}/${DB_NOME}?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  config:
    login-url: /auth/login
    type: encrypted